[Modify] list() is divided to core/list.fnc

diff --git a/bin/toybox b/bin/toybox
--- a/bin/toybox
+++ b/bin/toybox
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+. $TOYBOX_HOME/core/list.fnc
+
 # ----------------------------------------
 # Global variables
 # ----------------------------------------
@@ -100,7 +102,7 @@ function __is_container_running() {
     docker ps -a | grep ${project_name}_${1}_ | grep Up > /dev/null 2>&1
 }
 
-#function __list() {
+#function __applist() {
 #    if [ -f ${applist} ]; then
 #        cat ${applist} | awk 'BEGIN{ OFS=" " }
 #            function red(s) { printf "\033[1;31m%s\033[0m",s }
@@ -134,70 +136,70 @@ function __print_header() {
     echo ''
 }
 
-function __list() {
-
-    __print_header
-
-    if [ ! -f ${applist} ]; then
-        echo 'no application available.'
-
-    else
-        app_name="proxy"
-        . $TOYBOX_HOME/lib/proxy.fnc
-        for container in ${containers[@]}; do
-            __is_container_exist ${container}; local exist=$(( ${exist} + $? ))
-            __is_container_running ${container}; local running=$(( ${running} + $? ))
-        done
-
-
-        if [ ${exist} -eq 0 ] && [ ${running} -eq 0 ]; then
-            printf "proxy is "
-            printf "\033[1;32m%-10s\033[0m" "running"
-        else
-            printf "you must start proxy"
-        fi
-        printf "\n"
-
-        cat ${applist} | while read line; do
-
-            fqdn=$(echo ${line} | awk '{print $1}')
-            applist_grep_key=${fqdn}
-            app_name=$(echo ${line} | awk '{print $2}')
-            app_path=$(echo ${line} | awk '{print $4}')
-            compose_file="${app_path}/bin/docker-compose.yml"
-            src="$TOYBOX_HOME/src/${app_name}"
-            . $TOYBOX_HOME/lib/${app_name}.fnc
-
-            if [ ${app_name} = 'proxy' ]; then
-                continue
-            else
-                printf "http://%-35s" ${fqdn}
-            fi
-
-            printf "%-15s" ${app_name}:${app_version}
-
-            local exist=0
-            local running=0
-
-            for container in ${containers[@]}; do
-                __is_container_exist ${container}; exist=$(( ${exist} + $? ))
-                __is_container_running ${container}; running=$(( ${running} + $? ))
-            done
-
-            if [ ${exist} -eq ${#containers[@]} ]; then
-                printf "%-10s" "removed"
-            elif [ ${exist} -eq 0 ] && [ ${running} -eq 0 ]; then
-                printf "\033[1;32m%-10s\033[0m" "running"
-            elif [ ${exist} -eq 0 ] && [ ${running} -eq ${#containers[@]} ]; then
-                printf "\033[1;31m%-10s\033[0m" "stopped"
-            else
-                printf "\033[1;31m%-10s\033[0m" "error"
-            fi
-            printf "\n"
-
-        done
-    fi
-}
+#function __list() {
+#
+#    __print_header
+#
+#    if [ ! -f ${applist} ]; then
+#        echo 'no application available.'
+#
+#    else
+#        app_name="proxy"
+#        . $TOYBOX_HOME/lib/proxy.fnc
+#        for container in ${containers[@]}; do
+#            __is_container_exist ${container}; local exist=$(( ${exist} + $? ))
+#            __is_container_running ${container}; local running=$(( ${running} + $? ))
+#        done
+#
+#
+#        if [ ${exist} -eq 0 ] && [ ${running} -eq 0 ]; then
+#            printf "proxy is "
+#            printf "\033[1;32m%-10s\033[0m" "running"
+#        else
+#            printf "you must start proxy"
+#        fi
+#        printf "\n"
+#
+#        cat ${applist} | while read line; do
+#
+#            fqdn=$(echo ${line} | awk '{print $1}')
+#            applist_grep_key=${fqdn}
+#            app_name=$(echo ${line} | awk '{print $2}')
+#            app_path=$(echo ${line} | awk '{print $4}')
+#            compose_file="${app_path}/bin/docker-compose.yml"
+#            src="$TOYBOX_HOME/src/${app_name}"
+#            . $TOYBOX_HOME/lib/${app_name}.fnc
+#
+#            if [ ${app_name} = 'proxy' ]; then
+#                continue
+#            else
+#                printf "http://%-35s" ${fqdn}
+#            fi
+#
+#            printf "%-15s" ${app_name}:${app_version}
+#
+#            local exist=0
+#            local running=0
+#
+#            for container in ${containers[@]}; do
+#                __is_container_exist ${container}; exist=$(( ${exist} + $? ))
+#                __is_container_running ${container}; running=$(( ${running} + $? ))
+#            done
+#
+#            if [ ${exist} -eq ${#containers[@]} ]; then
+#                printf "%-10s" "removed"
+#            elif [ ${exist} -eq 0 ] && [ ${running} -eq 0 ]; then
+#                printf "\033[1;32m%-10s\033[0m" "running"
+#            elif [ ${exist} -eq 0 ] && [ ${running} -eq ${#containers[@]} ]; then
+#                printf "\033[1;31m%-10s\033[0m" "stopped"
+#            else
+#                printf "\033[1;31m%-10s\033[0m" "error"
+#            fi
+#            printf "\n"
+#
+#        done
+#    fi
+#}
 
 # ----------------------------------------
 # Command
