[Add] reset & logs function

diff --git a/bin/toybox b/bin/toybox
--- a/bin/toybox
+++ b/bin/toybox
@@ -10,6 +10,7 @@ version="0.1.0"
 applist="$TOYBOX_HOME/stack/applications.txt"
 compose_file=""
 fqdn=""
+port=""
 app_name=""
 app_path=""
 src=""
@@ -67,6 +68,10 @@ function __version() {
 
 function __help() { 
     __usage 
+}
+
+function __is_set_env() {
+    env | grep $1 > /dev/null 2>&1;
 }
 
 function __is_executable() {
@@ -128,8 +133,6 @@ function __monitor() {
     if [ ! -f ${applist} ]; then
         echo 'no application available.'
     else
-        echo '<Proxy>'
-        local count=0
 
         cat ${applist} | while read line; do
 
@@ -137,14 +140,13 @@ function __monitor() {
             app_name=$(echo ${line} | awk '{print $2}')
             app_path=$(echo ${line} | awk '{print $5}')
 
+            . $TOYBOX_HOME/lib/${app_name}.fnc
+
             if [ ${app_name} = 'proxy' ]; then
-                count=$(expr ${count} + 1)
-                printf "%2s: " ${count}
-    
-                printf "%-42s" "n/a" # URL
-                printf "%-15s" ${app_name}:${app_version}
-                __is_container_exist ${app_name}; local exist_main=$?
-                local exist_docker_gen=$?
+                printf "proxy is "
+                
+                __is_container_exist ${main_container}; local exist_main=$?
+                __is_container_exist ${docker_gen_container}; local exist_docker_gen=$?
                 local result=$(expr ${exist_main} + ${exist_docker_gen})
 
                 # print status running|stopped|removed|error
@@ -153,7 +155,7 @@ function __monitor() {
                 elif [ ${result} -eq 1 ]; then
                     printf "\033[1;31m%-10s\033[0m" "error"
                 elif [ ${result} -eq 0 ]; then
-                    if __is_container_running ${app_name}; then
+                    if __is_container_running ${main_container}; then
                         printf "\033[1;32m%-10s\033[0m" "running"
                     else
                         printf "\033[1;31m%-10s\033[0m" "stopped"
@@ -311,18 +313,27 @@ function _start() {
 
 function _stop() {
     if [ ${app_name} = "proxy" ]; then
-        __stop
+       cd ${app_path}/bin
+       docker-compose -p ${project_name} stop && {
+           if [ -f ${applist} ]; then
+               local old=$(cat ${applist} | grep ${port})
+               local new=$(cat ${applist} | grep ${port} | sed -e "s:running:stopped:")
+               sed -i -e "s:${old}:${new}:" ${applist}
+           else
+               echo "error@_stop() in toybox"
+           fi
+       }
     else
-        cd ${app_path}/bin
-        docker-compose -p ${project_name} stop && {
-            if [ -f ${applist} ]; then
-                local old=$(cat ${applist} | grep ${fqdn})
-                local new=$(cat ${applist} | grep ${fqdn} | sed -e "s:running:stopped:")
-                sed -i -e "s:${old}:${new}:" ${applist}
-            else
-                echo "error@_stop() in toybox"
-            fi
-        }
+       cd ${app_path}/bin
+       docker-compose -p ${project_name} stop && {
+           if [ -f ${applist} ]; then
+               local old=$(cat ${applist} | grep ${fqdn})
+               local new=$(cat ${applist} | grep ${fqdn} | sed -e "s:running:stopped:")
+               sed -i -e "s:${old}:${new}:" ${applist}
+           else
+               echo "error@_stop() in toybox"
+           fi
+       }
     fi
 }
 
@@ -370,6 +381,12 @@ function _clear() {
 }
 
 
+function _logs() {
+    echo ${app_path}
+    cd ${app_path}/bin
+    docker-compose -p ${project_name} logs
+}
+
 function _ps() {
     echo ${app_path}
     cd ${app_path}/bin
@@ -391,6 +408,7 @@ function _ps() {
 function __docker_toybox() {
     # Load application module
     if [ -e $TOYBOX_HOME/lib/${app_name}.fnc ]; then
+        echo 'hogehoge'
         . $TOYBOX_HOME/lib/${app_name}.fnc
         mkdir -p ${app_path}
     else
@@ -407,16 +425,6 @@ function __docker_toybox() {
         echo "See '${project_name} -h'." 
         exit 1
     fi
-}
-
-function __red() { 
-    printf "\033[1;31m%s\033[0m" $1
-}
-function __green() { 
-    printf "\033[1;32m%s\033[0m" $1
-}
-function __blue() { 
-    printf "\033[1;34m%s\033[0m" $1
 }
 
 # ----------------------------------------
@@ -440,15 +448,24 @@ EOF
     exit 1
   }
 
-# check $TOYBOX_HOME
-if [ -z "$TOYBOX_HOME" ] ; then
+__is_set_env TOYBOX_HOME || {
     cat <<EOF
 toybox: "TOYBOX_HOME" is not set. 
 Please set it for your absolute path of the docker-toybox installed directory
 e.g. export TOYBOX_HOME=/home/nobita/workspace/docker-toybox
 EOF
     exit 1
-fi
+}
+
+# check $TOYBOX_HOME
+#if [ -z "$TOYBOX_HOME" ] ; then
+#    cat <<EOF
+#toybox: "TOYBOX_HOME" is not set. 
+#Please set it for your absolute path of the docker-toybox installed directory
+#e.g. export TOYBOX_HOME=/home/nobita/workspace/docker-toybox
+#EOF
+#    exit 1
+#fi
 
 # check options
 while getopts evhs:d: OPT
@@ -467,77 +484,96 @@ shift $(expr $OPTIND - 1)
 if [ $# -eq 0 ]; then
     #__list
     __monitor
-    exit 0
 
-elif [ $# -ne 2 ]; then
-    __usage
-    exit 1
-fi
-
-# ----------------------------------------
-# set variables
-# ----------------------------------------
-
-arg=$1; shift
-
-# URL argument
-if [[ ${arg} =~ ^http://.* ]]; then
-    
-    fqdn=$(echo ${arg} | sed "s?http://??")
-
-    if [ ! -f ${applist} ]; then
-        echo "${project_name}: No application available."
-        echo "Please create application first."
-        exit 1
-    fi
-
-    app_name="$(cat ${applist} | grep ${fqdn} | awk '{print $2}')"
-    app_path="$(cat ${applist} | grep ${fqdn} | awk '{print $4}')"
-    compose_file="${app_path}/bin/docker-compose.yml"
-    src="$TOYBOX_HOME/src/${app_name}"
-    
-    if [ ! -n "${app_name}" ] && [ ! -n "${app_path}" ]; then
-        echo "${project_name}: 'http://${fqdn}' may be invalid URL."
-        exit 1
-    fi
-
-# Generic Form
-elif [ ${arg} = "proxy" ]; then
-    port=80
-    app_name=${arg}
-    app_path="$TOYBOX_HOME/stack/${app_name}/${port}"
-    compose_file="${app_path}/bin/docker-compose.yml"
-    src="$TOYBOX_HOME/src/${app_name}"
-
-else
-    app_name_temp=${arg}
-    app_name=$(echo ${app_name_temp} | cut -d":" -f1)
-    app_version=$(echo ${app_name_temp} | cut -d":" -f2)
-
-    # set FQDN
-    if [ "${domain}" = '' ]; then
-        if [ -z "$TOYBOX_DOMAIN" ] ; then
-            domain=docker-toybox.com
-        else
-            domain=$TOYBOX_DOMAIN
+elif [ $# -eq 1 ]; then
+    if [ $1 = "reset" ]; then
+        echo "Are you sure you want to reset all of containers related ${project_name}?(y/n)"
+        read answer
+        if [ ${answer} = "y" ]; then
+            echo -n 'docker stop...'
+            docker stop $(docker ps | grep ${project_name} | awk '{print $1}') > /dev/null 2>&1
+            echo 'done.'
+            echo -n 'docker rm...'
+            docker rm $(docker ps -a | grep ${project_name} | awk '{print $1}') > /dev/null 2>&1
+            echo 'done.'
+            echo -n 'remove stack directory...'
+            sudo rm -rf $TOYBOX_HOME/stack && {
+                echo 'done.'
+            }
+            
         fi
     fi
-    if [ "${sub_domain}" = '' ]; then
-        sub_domain=${app_name}
-    fi
 
-    fqdn="${sub_domain}.${domain}"
-    app_path="$TOYBOX_HOME/stack/${app_name}/${sub_domain}.${domain}"
-    compose_file="${app_path}/bin/docker-compose.yml"
-    src="$TOYBOX_HOME/src/${app_name}"
-   
-    if [ $1 != "new" ]; then
-        echo ${project_name}": Invalid argument(s)."
-        echo "See '${project_name} -h'." 
-        exit 1
+#elif [ $# -ne 2 ]; then
+#    __usage
+#
+elif [ $# -eq 2 ]; then
+
+    arg=$1; shift
+    
+    # ----------------------------------------
+    # set variables: URL form
+    # ----------------------------------------
+    if [[ ${arg} =~ ^http://.* ]]; then
+        
+        fqdn=$(echo ${arg} | sed "s?http://??")
+    
+        if [ ! -f ${applist} ]; then
+            echo "${project_name}: No application available."
+            echo "Please create application first."
+            exit 1
+        fi
+    
+        app_name="$(cat ${applist} | grep ${fqdn} | awk '{print $2}')"
+        app_path="$(cat ${applist} | grep ${fqdn} | awk '{print $4}')"
+        compose_file="${app_path}/bin/docker-compose.yml"
+        src="$TOYBOX_HOME/src/${app_name}"
+        
+        if [ ! -n "${app_name}" ] && [ ! -n "${app_path}" ]; then
+            echo "${project_name}: 'http://${fqdn}' may be invalid URL."
+            exit 1
+        fi
+    
+    else
+        # ----------------------------------------
+        # set variables: Generic Form
+        # ----------------------------------------
+        if [ ${arg} = "proxy" ]; then
+            port=80
+            app_name=${arg}
+            app_path="$TOYBOX_HOME/stack/${app_name}/${port}"
+            compose_file="${app_path}/bin/docker-compose.yml"
+            src="$TOYBOX_HOME/src/${app_name}"
+        else
+            app_name_temp=${arg}
+            app_name=$(echo ${app_name_temp} | cut -d":" -f1)
+            app_version=$(echo ${app_name_temp} | cut -d":" -f2)
+        
+            # set FQDN
+            if [ "${domain}" = '' ]; then
+                if [ -z "$TOYBOX_DOMAIN" ] ; then
+                    domain=docker-toybox.com
+                else
+                    domain=$TOYBOX_DOMAIN
+                fi
+            fi
+            if [ "${sub_domain}" = '' ]; then
+                sub_domain=${app_name}
+            fi
+        
+            fqdn="${sub_domain}.${domain}"
+            app_path="$TOYBOX_HOME/stack/${app_name}/${sub_domain}.${domain}"
+            compose_file="${app_path}/bin/docker-compose.yml"
+            src="$TOYBOX_HOME/src/${app_name}"
+           
+            if [ $1 != "new" ]; then
+                echo ${project_name}": Invalid argument(s)."
+                echo "See '${project_name} -h'." 
+                exit 1
+            fi
+        fi
     fi
+    __docker_toybox $@
 fi
-
-__docker_toybox $@
 
 exit 0
